import {useEffect,useState} from "react";
import {isPlatformConfigured,platformGet,platformMutate,type PlatformMe} from "../../../platform/api";
import {matchCompatibility} from "../../../platform/matchCompatibility";

type Post={id:string;kind:string;target:string;role:string;looking_for:string;beginner_ok:number;capacity:number;current_members:number;expires_at:string};
type Party={post:{id:string;target:string;room_id:string;state:string;expires_at:string;capacity:number};members:Array<{user_id:string;nickname:string;role:string;ready:number}>};
export function PartyBoard({locale,me,deck,onRoom}:{locale:"ko"|"en";me:PlatformMe|null;deck:readonly string[];onRoom:(id:string,title:string)=>void}){
  const ko=locale==="ko";
  const[kind,setKind]=useState<"coop"|"crit">("coop");const[role,setRole]=useState<"dealer"|"support"|"balanced">("balanced");
  const[lookingFor,setLookingFor]=useState("any");const[target,setTarget]=useState("");const[minutes,setMinutes]=useState(60);const[beginner,setBeginner]=useState(true);
  const[posts,setPosts]=useState<Post[]>([]);const[party,setParty]=useState<Party|null>(null);const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
  const refresh=()=>isPlatformConfigured()?platformGet<{posts:Post[]}>(`/api/v1/matchmaking/open?kind=${kind}`).then((r)=>setPosts(r.posts)):Promise.resolve();
  useEffect(()=>{void refresh().catch(()=>setNotice(ko?"모집 목록을 불러오지 못했습니다.":"Could not load recruitment."));},[kind]);
  useEffect(()=>{if(!party)return;const timer=setInterval(()=>{void platformGet<Party>(`/api/v1/matchmaking/${party.post.id}`).then(setParty).catch(()=>setNotice(ko?"파티 연결을 확인해 주세요.":"Check your party connection."));},10000);return()=>clearInterval(timer);},[party?.post.id]);
  const action=async(run:()=>Promise<void>)=>{setBusy(true);try{await run();setNotice("");}catch(error){setNotice(error instanceof Error?error.message:"request_failed");}finally{setBusy(false);}};
  const create=()=>{if(!me)return;void action(async()=>{const result=await platformMutate<{id:string}>("/api/v1/matchmaking",{kind,target,role,lookingFor,deck:[...deck],beginnerOk:beginner,capacity:2,expiresInMinutes:minutes},me.csrf);setParty(await platformGet<Party>(`/api/v1/matchmaking/${result.id}`));await refresh();});};
  const join=(post:Post)=>{if(!me)return;void action(async()=>{await platformMutate(`/api/v1/matchmaking/${post.id}/join`,{role},me.csrf);setParty(await platformGet<Party>(`/api/v1/matchmaking/${post.id}`));await refresh();});};
  const ready=(value:boolean)=>{if(!me||!party)return;void action(async()=>{await platformMutate(`/api/v1/matchmaking/${party.post.id}/ready`,{ready:value},me.csrf,"PUT");setParty(await platformGet<Party>(`/api/v1/matchmaking/${party.post.id}`));});};
  const leave=()=>{if(!me||!party)return;void action(async()=>{await platformMutate(`/api/v1/matchmaking/${party.post.id}/leave`,{},me.csrf);setParty(null);await refresh();});};
  const own=party?.members.find((member)=>member.user_id===me?.user.id);
  const sorted=posts.map((post)=>({post,match:matchCompatibility({role,kind,beginner:false},post)})).sort((a,b)=>b.match.score-a.match.score);
  return <section className="v58-match"><header><div><small>PARTY MATCHING</small><h2>{ko?"역할에 맞는 파티 찾기":"Find a compatible party"}</h2><p>{ko?"적합도는 모드와 역할 조건을 비교한 점수이며 성공 확률이 아닙니다.":"Compatibility compares mode and roles; it is not a success probability."}</p></div></header>
    <div className="v58-online-layout"><div className="v58-compose"><label>{ko?"모드":"Mode"}<select value={kind} onChange={(e)=>setKind(e.target.value as typeof kind)}><option value="coop">{ko?"협동":"Co-op"}</option><option value="crit">{ko?"치피작":"Critical"}</option></select></label><label>{ko?"내 역할":"My role"}<select value={role} onChange={(e)=>setRole(e.target.value as typeof role)}><option value="dealer">{ko?"딜러":"Dealer"}</option><option value="support">{ko?"서포터":"Support"}</option><option value="balanced">{ko?"혼합":"Balanced"}</option></select></label><label>{ko?"모집 목표":"Target"}<input maxLength={80} value={target} onChange={(e)=>setTarget(e.target.value)} placeholder={ko?"예: 협동 100웨이브":"e.g. Co-op wave 100"}/></label><label>{ko?"찾는 역할":"Looking for"}<select value={lookingFor} onChange={(e)=>setLookingFor(e.target.value)}><option value="any">{ko?"누구나":"Any"}</option><option value="dealer">{ko?"딜러":"Dealer"}</option><option value="support">{ko?"서포터":"Support"}</option></select></label><label>{ko?"모집 유지 시간":"Recruitment duration"}<select value={minutes} onChange={(e)=>setMinutes(Number(e.target.value))}><option value={30}>30 min</option><option value={60}>60 min</option><option value={120}>120 min</option></select></label><label><input type="checkbox" checked={beginner} onChange={(e)=>setBeginner(e.target.checked)}/>{ko?"초보 참여 가능":"Beginners welcome"}</label><button disabled={!me||busy||!target.trim()||deck.length!==5||Boolean(party)} onClick={create}>{ko?"현재 덱으로 모집":"Recruit with current deck"}</button></div>
    <div>{party&&<section className="v58-sync"><h3>{party.post.target}</h3><p>{party.members.length===party.post.capacity&&party.members.every((member)=>member.ready)?(ko?"모두 준비 완료":"Everyone is ready"):(ko?"준비 상태 확인":"Ready check")}</p>{party.members.map((member)=><p key={member.user_id}>{member.nickname} · {member.role} · {member.ready?(ko?"준비 완료":"Ready"):(ko?"준비 중":"Not ready")}</p>)}{party.members.filter((member)=>member.role==="dealer").length>1&&<p>{ko?"딜러 역할이 겹칩니다. 서포터 구성을 확인하세요.":"Dealer roles overlap. Check support coverage."}</p>}<button disabled={busy} onClick={()=>ready(!own?.ready)}>{own?.ready?(ko?"준비 취소":"Not ready"):(ko?"준비 완료":"Ready")}</button><button onClick={()=>onRoom(party.post.room_id,party.post.target)}>{ko?"파티 채팅":"Party chat"}</button><button disabled={busy} onClick={leave}>{ko?"파티 나가기":"Leave party"}</button></section>}
    {sorted.map(({post,match})=><article className="v58-party-card" key={post.id}><h3>{post.target}</h3><p>{ko?"매칭 적합도":"Compatibility"} {match.score}/100 · {post.role} → {post.looking_for}</p><p>{match.reasons.includes("complementary_roles")?(ko?"딜러·서포터 역할이 보완됩니다.":"Dealer and support roles complement each other."):(ko?"요청 역할과 모집 조건을 확인하세요.":"Review role requirements.")}</p><time>{new Date(post.expires_at).toLocaleString()} · {post.current_members}/{post.capacity}</time><button disabled={!me||busy||Boolean(party)||!match.eligible} onClick={()=>join(post)}>{ko?"참가":"Join"}</button></article>)}{!posts.length&&<p className="v58-empty">{ko?"현재 모집 중인 파티가 없습니다.":"No open parties."}</p>}</div></div>{notice&&<p role="status">{notice}</p>}</section>;
}
